"""add_game_time_and_over_under

Revision ID: 8405f605970d
Revises: 7a225b448ce2
Create Date: 2025-11-20 16:41:22.986651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8405f605970d'
down_revision: Union[str, Sequence[str], None] = '7a225b448ce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('game_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('game', sa.Column('over_under', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'over_under')
    op.drop_column('game', 'game_time')
    # ### end Alembic commands ###
